import Foundation
import Combine

/// `nonisolated` because these are pure value types that have to be readable away from the UI:
/// `ConversationExport` encodes a whole transcript — potentially with embedded image data — off
/// the main actor precisely so a long chat doesn't block it. Nothing here is mutable shared state.
nonisolated struct ChatMessage: Identifiable, Codable, Equatable {
    var id: UUID = UUID()
    var isUser: Bool
    var text: String
    var timestamp: Date = Date()
    /// JPEG data for AI-generated images. nil for text-only messages.
    var imageData: Data? = nil
    /// Set on an assistant message that's offering to search the web for the preceding user
    /// message — holds that original user text so the search can be re-classified and run when
    /// the user taps through. Cleared the moment the user picks Search or No; a still-pending
    /// offer surviving to the next launch just harmlessly re-shows the same two buttons rather
    /// than needing any special recovery handling.
    var pendingSearchQuery: String? = nil

    var isImageMessage: Bool { imageData != nil }
}

nonisolated struct Conversation: Identifiable, Codable, Equatable {
    var id: UUID = UUID()
    var title: String
    var messages: [ChatMessage]
    var createdAt: Date = Date()
    /// A private conversation is held in memory only and never written to disk. Optional with
    /// a default so conversations persisted before this flag existed still decode.
    var isPrivate: Bool = false
}

class ConversationManager: ObservableObject {
    @Published var conversations: [Conversation] = []
    @Published var activeConversationId: UUID? = nil

    /// Marks the active conversation as private — it stays in memory and is dropped when the
    /// app quits.
    ///
    /// This used to be a global "stealth mode" that short-circuited `saveConversations()`
    /// entirely, which silently discarded *every* pending change while it was on: deleting a
    /// different chat, or renaming one, appeared to work and then came back on next launch.
    /// Scoping privacy to the individual conversation makes the guarantee precise (this chat is
    /// never written) without holding the rest of the user's data hostage.
    @Published var privateMode: Bool = false {
        didSet {
            guard let activeId = activeConversationId,
                  let index = conversations.firstIndex(where: { $0.id == activeId }) else { return }
            conversations[index].isPrivate = privateMode
            if privateMode {
                // Remove any already-persisted copy of this conversation the moment it is
                // marked private — otherwise turning privacy on mid-chat leaves the earlier
                // half of it on disk, which is exactly the promise being made here.
                persist()
            } else {
                saveConversations()
            }
        }
    }

    private let storageKey = "DarkAI_Conversations"

    init() {
        loadConversations()
    }

    func loadConversations() {
        if let data = UserDefaults.standard.data(forKey: storageKey),
           let decoded = try? JSONDecoder().decode([Conversation].self, from: data) {
            self.conversations = decoded
            if let first = decoded.first {
                self.activeConversationId = first.id
            }
        } else {
            let firstChat = Conversation(
                title: "Welcome",
                messages: [
                    ChatMessage(isUser: false, text: "Welcome to \(AppInfo.displayName). Everything here runs on your device — no account needed. Load a model in Settings and start typing.\n\nResponses are generated by a model on this phone and can be wrong, so check anything important. There's an optional, off-by-default internet search feature in Settings — the app will always ask before using it.")
                ]
            )
            self.conversations = [firstChat]
            self.activeConversationId = firstChat.id
            saveConversations()
        }
    }

    func saveConversations() {
        persist()
    }

    /// Writes everything except conversations flagged private.
    private func persist() {
        let persistable = conversations.filter { !$0.isPrivate }
        if let encoded = try? JSONEncoder().encode(persistable) {
            UserDefaults.standard.set(encoded, forKey: storageKey)
        }
    }

    /// Whether the active conversation is currently excluded from disk.
    var isActiveConversationPrivate: Bool {
        activeConversation?.isPrivate ?? false
    }
    
    var activeConversation: Conversation? {
        conversations.first(where: { $0.id == activeConversationId })
    }
    
    func createConversation() {
        let newChat = Conversation(title: "Chat \(conversations.count + 1)", messages: [])
        conversations.insert(newChat, at: 0)
        activeConversationId = newChat.id
        privateMode = false
        saveConversations()
    }
    
    func deleteConversation(id: UUID) {
        conversations.removeAll(where: { $0.id == id })
        if activeConversationId == id {
            activeConversationId = conversations.first?.id
        }
        if conversations.isEmpty {
            createConversation()
        } else {
            saveConversations()
        }
    }
    
    func selectConversation(id: UUID) {
        activeConversationId = id
        // Keep the toggle showing the state of the chat actually on screen, rather than
        // carrying the previous chat's setting over to one it was never applied to.
        let isPrivate = conversations.first(where: { $0.id == id })?.isPrivate ?? false
        if privateMode != isPrivate { privateMode = isPrivate }
    }

    /// Removes a single message. Used by the content-report flow, which has to take the
    /// offending content out of the conversation the moment it is reported.
    func deleteMessage(id: UUID) {
        guard let activeId = activeConversationId,
              let index = conversations.firstIndex(where: { $0.id == activeId }) else { return }
        conversations[index].messages.removeAll { $0.id == id }
        saveConversations()
        objectWillChange.send()
    }
    
    func addMessageToActive(isUser: Bool, text: String) {
        guard let activeId = activeConversationId else { return }
        
        if let index = conversations.firstIndex(where: { $0.id == activeId }) {
            let msg = ChatMessage(isUser: isUser, text: text)
            conversations[index].messages.append(msg)
            
            // Auto update title if it was default and has messages now
            if conversations[index].title.hasPrefix("Chat ") && isUser {
                let cleanTitle = text.prefix(20).trimmingCharacters(in: .whitespacesAndNewlines)
                conversations[index].title = cleanTitle.isEmpty ? "Chat" : String(cleanTitle) + "..."
            }
            
            saveConversations()

            objectWillChange.send()
        }
    }
    
    /// Appends an assistant message offering to search the web, with the original user query
    /// attached via `pendingSearchQuery` so the confirm/decline buttons know what to act on.
    func addSearchOfferToActive(text: String, query: String) {
        guard let activeId = activeConversationId else { return }
        if let index = conversations.firstIndex(where: { $0.id == activeId }) {
            var msg = ChatMessage(isUser: false, text: text)
            msg.pendingSearchQuery = query
            conversations[index].messages.append(msg)
            saveConversations()
            objectWillChange.send()
        }
    }

    /// Clears the pending-search flag on a specific message, so its buttons stop rendering.
    /// Called the moment the user picks either Search or No — the offer is a one-shot choice.
    /// Keyed by message ID rather than "the last message": a user can send a new message before
    /// answering an older offer (nothing blocks that), so the offer being answered isn't
    /// guaranteed to still be the last one in the conversation.
    func clearPendingSearch(messageId: UUID) {
        guard let activeId = activeConversationId,
              let index = conversations.firstIndex(where: { $0.id == activeId }),
              let messageIndex = conversations[index].messages.firstIndex(where: { $0.id == messageId }) else { return }
        conversations[index].messages[messageIndex].pendingSearchQuery = nil
        saveConversations()
    }

    func updateLastMessage(text: String) {
        guard let activeId = activeConversationId else { return }
        if let index = conversations.firstIndex(where: { $0.id == activeId }),
           !conversations[index].messages.isEmpty {
            let lastIndex = conversations[index].messages.count - 1
            conversations[index].messages[lastIndex].text = text
        }
    }

    /// Appends a completed AI-generated image message to the active conversation.
    func addImageMessageToActive(prompt: String, imageData: Data) {
        guard let activeId = activeConversationId else { return }
        if let index = conversations.firstIndex(where: { $0.id == activeId }) {
            let msg = ChatMessage(isUser: false, text: prompt, imageData: imageData)
            conversations[index].messages.append(msg)
            saveConversations()
            objectWillChange.send()
        }
    }

    /// Updates the imageData of the last message (used while generation completes).
    func updateLastMessageImage(imageData: Data) {
        guard let activeId = activeConversationId else { return }
        if let index = conversations.firstIndex(where: { $0.id == activeId }),
           !conversations[index].messages.isEmpty {
            let lastIndex = conversations[index].messages.count - 1
            conversations[index].messages[lastIndex].imageData = imageData
        }
    }
}
