//
//  LLMManager.swift
//  DarkAI
//
//  Real llama.cpp inference using the raw C API via LlamaSwift (mattt/llama.swift).
//  All responses are generated by the model — zero hardcoded text.
//

import Foundation
import Combine
import LlamaSwift
import os
import UIKit

// MARK: - State Types

enum ModelLoadState {
    case unloaded
    case loading(progress: Double, status: String)
    case loaded(modelName: String, sizeGB: Double)
    case failed(error: String)
}

enum MemorySafetyStatus: Equatable {
    case safe
    case warning(requiredGB: Double, availableGB: Double)
    case dangerous(requiredGB: Double, availableGB: Double)
}

// MARK: - LlamaRunner Actor
// Wraps the raw llama.cpp C-API in a background actor to keep inference off the main thread.

actor LlamaRunner {

    private var model: OpaquePointer? = nil
    private var context: OpaquePointer? = nil
    private var nCtxTokens: Int = 2048  // actual context window in tokens
    private var isCancelled = false

    var isLoaded: Bool { model != nil && context != nil }

    init() {
        // Initialize the backend once for the lifetime of this actor
        llama_backend_init()
    }

    func load(path: String, availableMemoryGB: Double, modelSizeGB: Double) throws {
        // Unload any existing model first (does NOT touch the backend)
        unloadModelOnly()

        var modelParams = llama_model_default_params()

        // Dynamically calculate safe GPU offloading
        if modelSizeGB + 1.0 > availableMemoryGB * 0.85 {
            modelParams.n_gpu_layers = 16 // Offload only some layers
        } else {
            modelParams.n_gpu_layers = 99 // Full offload is safe
        }

        guard let mdl = llama_model_load_from_file(path, modelParams) else {
            throw NSError(domain: "LlamaRunner", code: 1,
                          userInfo: [NSLocalizedDescriptionKey: "Failed to load GGUF. Check the file is a valid model and fits in RAM."])
        }
        self.model = mdl

        // Query the model's trained context size — cap at 2048 for safety
        let trainedCtx = llama_model_n_ctx_train(mdl)
        let nCtx = max(512, min(Int32(trainedCtx), 2048))

        var ctxParams = llama_context_default_params()
        ctxParams.n_ctx   = UInt32(nCtx)
        ctxParams.n_batch = UInt32(min(nCtx, 512))
        ctxParams.n_threads       = Int32(max(1, ProcessInfo.processInfo.processorCount - 1))
        ctxParams.n_threads_batch = ctxParams.n_threads
        ctxParams.flash_attn_type = LLAMA_FLASH_ATTN_TYPE_ENABLED

        guard let ctx = llama_init_from_model(mdl, ctxParams) else {
            llama_model_free(mdl)
            self.model = nil
            throw NSError(domain: "LlamaRunner", code: 2,
                          userInfo: [NSLocalizedDescriptionKey: "Failed to create inference context. The model may require more RAM."])
        }
        self.context = ctx
        self.nCtxTokens = Int(nCtx)
    }

    /// Unloads only the model+context, leaving the backend alive for the next load.
    func unloadModelOnly() {
        isCancelled = true  // Stop any ongoing generation
        if let ctx = context { llama_free(ctx) }
        if let mdl = model   { llama_model_free(mdl) }
        context = nil
        model   = nil
        isCancelled = false
    }

    /// Full teardown — call only when the actor itself is being destroyed.
    func unload() {
        isCancelled = true
        if let ctx = context { llama_free(ctx) }
        if let mdl = model   { llama_model_free(mdl) }
        context = nil
        model   = nil
        llama_backend_free()
    }

    func requestCancel() {
        isCancelled = true
    }

    /// Tokenizes a string. Returns empty array on failure.
    private func tokenize(_ text: String, addBOS: Bool) -> [llama_token] {
        guard let mdl = model else { return [] }
        let vocab = llama_model_get_vocab(mdl)
        let utf8 = text.utf8
        let nTokensMax = Int32(utf8.count + 8)
        var tokens = [llama_token](repeating: 0, count: Int(nTokensMax))
        let n = llama_tokenize(vocab, text, Int32(utf8.count), &tokens, nTokensMax, addBOS, false)
        guard n > 0 else { return [] }
        return Array(tokens.prefix(Int(n)))
    }

    /// Checks whether the loaded model advertises any vision/multimodal capability via its metadata.
    func supportsVision() -> Bool {
        guard let mdl = model else { return false }
        // Check model metadata key for projector or mmproj type
        let count = llama_model_meta_count(mdl)
        for i in 0..<count {
            var keyBuf = [CChar](repeating: 0, count: 512)
            llama_model_meta_key_by_index(mdl, i, &keyBuf, 512)
            let key = String(cString: keyBuf).lowercased()
            if key.contains("vision") || key.contains("clip") || key.contains("mmproj") || key.contains("multimodal") {
                return true
            }
        }
        return false
    }

    /// Runs autoregressive inference and streams results via the continuation.
    func generateStream(
        messages: [(role: String, content: String)],
        maxTokens: Int,
        continuation: AsyncStream<String>.Continuation
    ) {
        guard let ctx = context, let mdl = model else {
            continuation.finish()
            return
        }

        isCancelled = false

        let vocab = llama_model_get_vocab(mdl)

        // --- Apply Native Chat Template ---
        var cStrings: [[CChar]] = []
        for msg in messages {
            cStrings.append(msg.role.cString(using: .utf8) ?? [])
            cStrings.append(msg.content.cString(using: .utf8) ?? [])
        }

        var chatStructs: [llama_chat_message] = []
        for i in 0..<messages.count {
            cStrings[i*2].withUnsafeBufferPointer { rPtr in
                cStrings[i*2 + 1].withUnsafeBufferPointer { cPtr in
                    chatStructs.append(llama_chat_message(role: rPtr.baseAddress, content: cPtr.baseAddress))
                }
            }
        }

        let tmpl = llama_model_chat_template(mdl, nil)
        var tmplBuf = [CChar](repeating: 0, count: 32768)
        let formattedLen = llama_chat_apply_template(tmpl, chatStructs, chatStructs.count, true, &tmplBuf, Int32(tmplBuf.count))

        let finalPrompt: String
        if formattedLen > 0 && formattedLen < tmplBuf.count {
            finalPrompt = String(cString: tmplBuf)
        } else {
            // Fallback for models missing a template
            finalPrompt = messages.map { "\($0.role): \($0.content)" }.joined(separator: "\n") + "\nassistant:\n"
        }

        // 1. Tokenize prompt — guard against exceeding the context window
        var promptTokens = tokenize(finalPrompt, addBOS: true)
        guard !promptTokens.isEmpty else {
            continuation.yield("[Error: tokenization returned empty]")
            continuation.finish()
            return
        }

        // Clamp to context window minus headroom for generation
        let maxPromptTokens = max(1, nCtxTokens - min(maxTokens, nCtxTokens / 2))
        if promptTokens.count > maxPromptTokens {
            // Keep the first 250 tokens (template tags + system prompt) and the tail
            let keepStart = min(promptTokens.count, 250)
            let startTokens = promptTokens.prefix(keepStart)
            let neededEnd = max(0, maxPromptTokens - keepStart)
            let endTokens = promptTokens.suffix(neededEnd)
            promptTokens = Array(startTokens) + Array(endTokens)
        }

        // 2. Clear KV cache to prevent crashes across multiple prompts
        if let mem = llama_get_memory(ctx) {
            llama_memory_clear(mem, true)
        }

        // 3. Prefill (evaluate the prompt)
        var batch = llama_batch_init(Int32(promptTokens.count), 0, 1)
        defer { llama_batch_free(batch) }

        for (i, token) in promptTokens.enumerated() {
            batch.token[i] = token
            batch.pos[i] = Int32(i)
            batch.n_seq_id[i] = 1
            if let seqIdPtr = batch.seq_id[i] {
                seqIdPtr.pointee = 0
            }
            batch.logits[i] = (i == promptTokens.count - 1) ? 1 : 0
        }
        batch.n_tokens = Int32(promptTokens.count)

        if llama_decode(ctx, batch) != 0 {
            continuation.yield("[Error: prefill decode failed]")
            continuation.finish()
            return
        }

        // 4. Autoregressive decoding with temperature + top-p sampling to prevent repetition
        let eosToken = llama_vocab_eos(vocab)
        let nVocab = Int(llama_vocab_n_tokens(vocab))

        // IMPORTANT: Reset nPos each generation — previously unbounded growth caused crashes!
        var nPos = Int32(promptTokens.count)
        var generatedCount = 0

        // Sampling parameters — temperature prevents asterisk/repetition loops
        let temperature: Float = 0.7
        let topP: Float = 0.9
        let repeatPenalty: Float = 1.1
        var recentTokens = [llama_token]()

        var singleBatch = llama_batch_init(1, 0, 1)
        defer { llama_batch_free(singleBatch) }

        var accumulatedOutput = ""

        while generatedCount < maxTokens {
            guard !isCancelled else { break }

            guard let logitsPtr = llama_get_logits_ith(ctx, -1) else { break }

            // Copy logits to a Swift array for manipulation
            var logits = Array(UnsafeBufferPointer(start: logitsPtr, count: nVocab))

            // Apply repeat penalty
            for tok in recentTokens {
                let idx = Int(tok)
                if idx >= 0 && idx < nVocab {
                    if logits[idx] > 0 {
                        logits[idx] /= repeatPenalty
                    } else {
                        logits[idx] *= repeatPenalty
                    }
                }
            }

            // Temperature scaling
            if temperature > 0 {
                for i in 0..<nVocab { logits[i] /= temperature }
            }

            // Softmax
            let maxLogit = logits.max() ?? 0
            var expLogits = logits.map { expf($0 - maxLogit) }
            let sumExp = expLogits.reduce(0, +)
            if sumExp > 0 {
                for i in 0..<nVocab { expLogits[i] /= sumExp }
            }

            // Top-p nucleus sampling
            let sorted = expLogits.enumerated().sorted { $0.element > $1.element }
            var cumulative: Float = 0
            var nucleus: [(Int, Float)] = []
            for (idx, prob) in sorted {
                nucleus.append((idx, prob))
                cumulative += prob
                if cumulative >= topP { break }
            }

            // Sample from nucleus
            let nucleusSum = nucleus.reduce(0) { $0 + $1.1 }
            var rand = Float.random(in: 0..<nucleusSum)
            var sampledId = nucleus.first?.0 ?? 0
            for (idx, prob) in nucleus {
                rand -= prob
                if rand <= 0 {
                    sampledId = idx
                    break
                }
            }

            let bestId = llama_token(sampledId)

            if bestId == eosToken { break }

            // Detokenize
            var tokenBuf = [CChar](repeating: 0, count: 256)
            let nChars = llama_token_to_piece(vocab, bestId, &tokenBuf, 256, 0, false)
            if nChars > 0 {
                let piece = String(bytes: tokenBuf.prefix(Int(nChars)).map { UInt8(bitPattern: $0) }, encoding: .utf8) ?? ""
                if !piece.isEmpty {
                    accumulatedOutput += piece

                    // Stop String check — prevents models talking to themselves
                    let lower = accumulatedOutput.lowercased()
                    if lower.hasSuffix("[inst]") || lower.hasSuffix("user:") || lower.hasSuffix("<|im_end|>") || lower.hasSuffix("<start_of_turn>user") || lower.hasSuffix("<|user|>") {
                        break
                    }

                    continuation.yield(piece)
                }
            }

            // Track recent tokens for repeat penalty (sliding window of last 64)
            recentTokens.append(bestId)
            if recentTokens.count > 64 { recentTokens.removeFirst() }

            // Advance
            singleBatch.token[0] = bestId
            singleBatch.pos[0] = nPos
            singleBatch.n_seq_id[0] = 1
            if let seqIdPtr = singleBatch.seq_id[0] {
                seqIdPtr.pointee = 0
            }
            singleBatch.logits[0] = 1
            singleBatch.n_tokens = 1

            // Guard against exceeding context window — this was the multi-prompt crash cause
            guard nPos < Int32(nCtxTokens) - 1 else { break }

            if llama_decode(ctx, singleBatch) != 0 { break }

            nPos += 1
            generatedCount += 1
        }

        continuation.finish()
    }

    deinit {
        if let ctx = context { llama_free(ctx) }
        if let mdl = model   { llama_model_free(mdl) }
        llama_backend_free()
    }
}

// MARK: - LLMManager

@MainActor
class LLMManager: ObservableObject {
    @Published var loadState: ModelLoadState = .unloaded
    @Published var isGenerating: Bool = false
    @Published var systemMemoryGB: Double = 0.0
    @Published var activeModelURL: URL? = nil
    @Published var generationSpeed: Double = 0.0
    @Published var modelSupportsVision: Bool = false

    @Published var maxTokens: Int = UserDefaults.standard.object(forKey: "maxTokens") as? Int ?? 512 {
        didSet {
            UserDefaults.standard.set(maxTokens, forKey: "maxTokens")
        }
    }

    private let runner = LlamaRunner()

    init() {
        self.systemMemoryGB = getPhysicalMemory()
        setupAppLifecycleObservers()
    }

    // MARK: - App Lifecycle - Clean unload on background/termination

    private func setupAppLifecycleObservers() {
        NotificationCenter.default.addObserver(
            forName: UIApplication.willTerminateNotification,
            object: nil,
            queue: .main
        ) { [weak self] _ in
            Task { await self?.runner.unload() }
        }
        NotificationCenter.default.addObserver(
            forName: UIApplication.didReceiveMemoryWarningNotification,
            object: nil,
            queue: .main
        ) { [weak self] _ in
            guard let self else { return }
            Task {
                await self.runner.requestCancel()
                await self.runner.unloadModelOnly()
                await MainActor.run {
                    self.loadState = .failed(error: "System memory pressure — model unloaded safely. Reload when ready.")
                    self.activeModelURL = nil
                    self.modelSupportsVision = false
                }
            }
        }
    }

    // MARK: - Memory Utilities

    func getPhysicalMemory() -> Double {
        #if os(iOS)
        return Double(os_proc_available_memory()) / (1024.0 * 1024.0 * 1024.0)
        #else
        return Double(ProcessInfo.processInfo.physicalMemory) / (1024.0 * 1024.0 * 1024.0)
        #endif
    }

    func getModelSizeGB(at url: URL) -> Double {
        guard let size = try? url.resourceValues(forKeys: [.fileSizeKey]).fileSize else { return 0 }
        return Double(size) / (1024.0 * 1024.0 * 1024.0)
    }

    func checkMemorySafety(modelSizeGB: Double) -> MemorySafetyStatus {
        let total = systemMemoryGB
        let required = modelSizeGB + 1.5

        // Developer apps are capped at 6GB. Models under 6GB should not warn.
        if modelSizeGB < 6.0 {
            return .safe
        }

        if required > total * 0.90 {
            return .dangerous(requiredGB: required, availableGB: total)
        } else if required > total * 0.70 {
            return .warning(requiredGB: required, availableGB: total)
        }
        return .safe
    }

    // MARK: - Model Loading

    func loadModel(at url: URL, forceLoad: Bool = false) {
        let sizeGB = getModelSizeGB(at: url)
        let safety = checkMemorySafety(modelSizeGB: sizeGB)

        if case .dangerous = safety, !forceLoad {
            let req = String(format: "%.1f", sizeGB + 1.5)
            let avail = String(format: "%.1f", systemMemoryGB * 0.90)
            self.loadState = .failed(error: "Memory Failsafe: Model requires \(req) GB but only \(avail) GB is safely available.")
            return
        }

        activeModelURL = url
        self.loadState = .loading(progress: 0.1, status: "Initialising llama.cpp backend…")

        Task {
            do {
                await MainActor.run {
                    self.loadState = .loading(progress: 0.4, status: "Loading GGUF weights…")
                }

                let availMem = await MainActor.run { self.getPhysicalMemory() }

                try await runner.load(
                    path: url.path,
                    availableMemoryGB: availMem,
                    modelSizeGB: sizeGB
                )

                let hasVision = await runner.supportsVision()

                await MainActor.run {
                    self.loadState = .loaded(modelName: url.lastPathComponent, sizeGB: sizeGB)
                    self.modelSupportsVision = hasVision
                }
            } catch {
                await MainActor.run {
                    self.loadState = .failed(error: error.localizedDescription)
                    self.modelSupportsVision = false
                }
            }
        }
    }

    func unloadModel() {
        Task {
            await runner.requestCancel()
            await runner.unloadModelOnly()
        }
        activeModelURL = nil
        loadState = .unloaded
        modelSupportsVision = false
    }

    func cancelGeneration() {
        Task { await runner.requestCancel() }
        isGenerating = false
    }

    // MARK: - Inference

    func generateResponse(
        prompt: String,
        history: [ChatMessage],
        systemPrompt: String,
        memoriesContext: String,
        ragContext: String,
        onToken: @escaping (String) -> Void,
        onComplete: @escaping (String) -> Void
    ) {
        guard case .loaded = loadState else {
            let msg = "⚠️ No model loaded. Go to Settings and load a GGUF model first."
            onToken(msg); onComplete(msg)
            return
        }

        isGenerating = true

        // Build System Context
        var systemBlock = ""
        if !systemPrompt.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            systemBlock += systemPrompt.trimmingCharacters(in: .whitespacesAndNewlines) + "\n\n"
        }
        if !memoriesContext.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            systemBlock += memoriesContext.trimmingCharacters(in: .whitespacesAndNewlines) + "\n\n"
        }
        if !ragContext.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            systemBlock += ragContext.trimmingCharacters(in: .whitespacesAndNewlines) + "\n\n"
        }

        var swiftMessages: [(role: String, content: String)] = []

        // System context goes as the first message (system role).
        // Models that support 'system' role natively will use it;
        // llama_chat_apply_template fallback will fold it into the first user turn.
        if !systemBlock.isEmpty {
            swiftMessages.append(("system", systemBlock.trimmingCharacters(in: .whitespacesAndNewlines)))
        }

        // History — these are PRIOR turns only (current prompt is NOT included)
        for msg in history.suffix(8) {
            swiftMessages.append((msg.isUser ? "user" : "assistant", msg.text))
        }

        // Current user turn (added only once here)
        swiftMessages.append(("user", prompt))

        let tokenLimit = maxTokens

        Task {
            var accumulated = ""

            await MainActor.run { self.generationSpeed = 0.0 }
            let startTime = CFAbsoluteTimeGetCurrent()
            var tokenCount = 0

            let stream = AsyncStream<String> { continuation in
                Task {
                    await runner.generateStream(
                        messages: swiftMessages,
                        maxTokens: tokenLimit,
                        continuation: continuation
                    )
                }
            }

            for await piece in stream {
                guard isGenerating else { break }

                tokenCount += 1
                let elapsed = max(0.01, CFAbsoluteTimeGetCurrent() - startTime)
                let tps = Double(tokenCount) / elapsed

                await MainActor.run {
                    self.generationSpeed = tps
                    onToken(piece)
                }

                accumulated += piece
            }

            await MainActor.run {
                isGenerating = false
                onComplete(accumulated)
            }
        }
    }
}
